name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.12.x", "1.13.x", "1.17.x" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Install dependencies
      run: go mod vendor

    - name: Exclude vendor directory
      run: diff -u <(echo -n) <(gofmt -d $(find . -path ./vendor -prune -o -name '*.go' -print)) # exlude vendor dir

    - name: Test
      run: go test -v -race ./...

    - name: Vet
      run: go vet ./...
